#!/usr/bin/env node
// Generate platform-agnostic shims from the canonical Claude skill so the same
// playbook runs on agents that don't read Claude's plugin/Skill/hook format
// (Codex, opencode, Cursor, Gemini CLI).
//
// Inputs (source of truth):
//   - plugins/gnapi-scaffolding/skills/scaffold-nestjs-service/SKILL.md  (the playbook)
//   - portable/STANDARDS.md                                              (the house rules the hook injects on Claude)
// Output:
//   - AGENTS.md  (repo-root; read natively by Codex/opencode/Cursor, or point the tool's instructions file at it)
//
// Run: node portable/build-shims.mjs   (no dependencies)

import {readFileSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILL = join(
  ROOT,
  'plugins/gnapi-scaffolding/skills/scaffold-nestjs-service/SKILL.md'
);
const STANDARDS = join(ROOT, 'portable/STANDARDS.md');
const OUT = join(ROOT, 'AGENTS.md');

/** Split a markdown file's YAML frontmatter from its body. */
function parse(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return {frontmatter: '', body: md.trim()};
  return {frontmatter: m[1], body: m[2].trim()};
}

/** Pull a single scalar field out of YAML frontmatter (handles wrapped lines). */
function field(frontmatter, key) {
  const re = new RegExp(`^${key}:\\s*([\\s\\S]*?)(?=\\n\\S+:|$)`, 'm');
  const m = frontmatter.match(re);
  return m ? m[1].replace(/\s+/g, ' ').trim() : '';
}

const skill = parse(readFileSync(SKILL, 'utf8'));
const standards = parse(readFileSync(STANDARDS, 'utf8'));
const description = field(skill.frontmatter, 'description');

// Drop the standards file's own H1 + maintainer blockquote so only the rules
// embed under our generated heading.
const standardsRules = standards.body
  .replace(/^#\s.*\n/, '')
  .replace(/(^>.*\n?)+/m, '')
  .trim();

const agents = `<!-- GENERATED by portable/build-shims.mjs — do not edit by hand.
     Edit the sources (SKILL.md, portable/STANDARDS.md) and re-run the generator. -->

# AGENTS.md — Gnapi service scaffolding (portable)

Platform-agnostic port of the Claude \`scaffold-nestjs-service\` skill. On Claude
Code this runs as a plugin skill with automatic triggering and a PreToolUse hook
that injects the house standards. On other agents (Codex, opencode, Cursor,
Gemini CLI) there is no auto-trigger and no hook, so:

1. **Trigger manually.** When the user asks to create / scaffold / bootstrap a
   NestJS service for Gnapi, follow the playbook below.
   _Skill intent:_ ${description}
2. **Standards are inlined** (the hook can't fire here) — they apply to every
   source file you write this session.

---

## Gnapi coding standards (always apply)

${standardsRules}

---

## Playbook: scaffold-nestjs-service

${skill.body}
`;

writeFileSync(OUT, agents);
process.stdout.write(`Wrote ${OUT} (${agents.length} bytes)\n`);
