#!/usr/bin/env node
// Generate per-harness instruction trees from the canonical Claude sources, so
// the same skill + standards run on every agent ECC supports — without
// hand-maintaining N copies. One source of truth, many native outputs; the
// shims CI fails on any drift.
//
// Inputs (source of truth):
//   - plugins/gnapi-scaffolding/skills/scaffold-nestjs-service/SKILL.md  (the playbook)
//   - portable/STANDARDS.md                                              (the house rules the hook injects on Claude)
//
// Outputs (per harness, ECC-style fan-out):
//   - AGENTS.md                     universal entry (Codex, opencode, Cursor, Amp, Zed, Jules, ...)
//   - CLAUDE.md                     Claude pointer (native plugin does the real work)
//   - GEMINI.md                     Gemini CLI pointer
//   - .codex/AGENTS.md + config.toml   OpenAI Codex (project-local)
//   - .cursor/rules/gnapi.mdc       Cursor project rule (always-apply)
//   - .opencode/opencode.json       opencode (instructions -> AGENTS.md)
//   - .agent/AGENTS.md              Google Antigravity
//   - .agents/skills/<name>/SKILL.md   generic skills dir (native SKILL.md loaders)
//
// Run: node portable/build-shims.mjs   (no dependencies)

import {readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILL_PATH =
  'plugins/gnapi-scaffolding/skills/scaffold-nestjs-service/SKILL.md';
const SKILL = join(ROOT, SKILL_PATH);
const STANDARDS = join(ROOT, 'portable/STANDARDS.md');

const GENERATED = '<!-- GENERATED by portable/build-shims.mjs — do not edit by hand. Edit the sources (SKILL.md, portable/STANDARDS.md) and re-run the generator. -->';

/** Split a markdown file's YAML frontmatter from its body. */
function parse(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return {frontmatter: '', body: md.trim()};
  return {frontmatter: m[1], body: m[2].trim()};
}

/** Pull a single scalar field out of YAML frontmatter (handles wrapped lines). */
function field(frontmatter, key) {
  const re = new RegExp(`^${key}:\\s*([\\s\\S]*?)(?=\\n\\S+:|$)`, 'm');
  const m = frontmatter.match(re);
  return m ? m[1].replace(/\s+/g, ' ').trim() : '';
}

/** Write a file, creating parent dirs. Returns bytes written for the run log. */
function emit(relPath, content) {
  const abs = join(ROOT, relPath);
  mkdirSync(dirname(abs), {recursive: true});
  writeFileSync(abs, content);
  return `  ${relPath} (${content.length} b)`;
}

const skillRaw = readFileSync(SKILL, 'utf8');
const skill = parse(skillRaw);
const standards = parse(readFileSync(STANDARDS, 'utf8'));
const name = field(skill.frontmatter, 'name') || 'scaffold-nestjs-service';
const description = field(skill.frontmatter, 'description');

// Drop the standards file's own H1 + maintainer blockquote so only the rules
// embed under our generated heading.
const standardsRules = standards.body
  .replace(/^#\s.*\n/, '')
  .replace(/(^>.*\n?)+/m, '')
  .trim();

// Shared body: standards + playbook, self-contained (no hook, no auto-trigger).
const fullBody = `# Gnapi service scaffolding (portable)

Platform-agnostic port of the Claude \`${name}\` skill. On Claude Code this runs
as a plugin skill with automatic triggering and a PreToolUse hook that injects
the house standards. On other agents there is no auto-trigger and no hook, so:

1. **Trigger manually.** When the user asks to create / scaffold / bootstrap a
   NestJS service for Gnapi, follow the playbook below.
   _Skill intent:_ ${description}
2. **Standards are inlined** (the hook can't fire here) — they apply to every
   source file you write this session.

---

## Gnapi coding standards (always apply)

${standardsRules}

---

## Playbook: ${name}

${skill.body}`;

const md = (body) => `${GENERATED}\n\n${body}\n`;
const log = [];

// 1. Universal entry — read natively by Codex, opencode, Cursor, Amp, Zed, ...
log.push(emit('AGENTS.md', md(fullBody)));

// 2. Claude pointer — the native plugin (auto-trigger + hook) does the real work.
log.push(
  emit(
    'CLAUDE.md',
    md(`# CLAUDE.md

On **Claude Code**, install the native plugin — it provides automatic skill
triggering and the \`gnapi-standards\` PreToolUse hook (no manual steps):

\`\`\`shell
/plugin marketplace add gnapi-tech/gnapi-claude
/plugin install gnapi-scaffolding@gnapi-claude
\`\`\`

Skill source of truth: \`${SKILL_PATH}\`. The portable, flattened version for
every other harness is [\`AGENTS.md\`](AGENTS.md).`)
  )
);

// 3. Gemini CLI pointer — load AGENTS.md; skills activate via Gemini's mechanism.
log.push(
  emit(
    'GEMINI.md',
    md(`# GEMINI.md

Gemini CLI: follow [\`AGENTS.md\`](AGENTS.md) for the Gnapi house standards and
the NestJS scaffold playbook. If skills are installed via Gemini's
\`activate_skill\` mechanism, the canonical skill is \`${name}\`.`)
  )
);

// 4. OpenAI Codex — project-local instructions + a reference config.
log.push(emit('.codex/AGENTS.md', md(fullBody)));
log.push(
  emit(
    '.codex/config.toml',
    `#:schema https://developers.openai.com/codex/config-schema.json
# Gnapi — Codex reference config. Copy to ~/.codex/config.toml (global) or keep
# project-local. Codex reads AGENTS.md and .codex/AGENTS.md for instructions.
approval_policy = "on-request"
sandbox_mode = "workspace-write"
web_search = "live"
`
  )
);

// 5. Cursor — project rule, always applied.
log.push(
  emit(
    '.cursor/rules/gnapi.mdc',
    `---
description: Gnapi house coding standards + NestJS service scaffold playbook
globs:
alwaysApply: true
---
${GENERATED}

${fullBody}
`
  )
);

// 6. opencode — instructions point at the universal AGENTS.md (single source).
log.push(
  emit(
    '.opencode/opencode.json',
    `${JSON.stringify(
      {
        $schema: 'https://opencode.ai/config.json',
        instructions: ['AGENTS.md'],
      },
      null,
      2
    )}\n`
  )
);

// 7. Google Antigravity — config under .agent/.
log.push(emit('.agent/AGENTS.md', md(fullBody)));

// 8. Generic skills dir — harnesses with native SKILL.md loaders read the
//    canonical skill verbatim (frontmatter preserved for auto-discovery).
log.push(emit(`.agents/skills/${name}/SKILL.md`, skillRaw));

process.stdout.write(`Wrote ${log.length} shims:\n${log.join('\n')}\n`);
